import cv2
import numpy as np
import os
import random

os.makedirs('data/outlines', exist_ok=True)
os.makedirs('data/filled', exist_ok=True)

FIXED_SIZE = 40
CANVAS_SIZE = 512
NUM_IMAGES = 1000

"""
star structure/logic:
  - 10 vertices (times we loop)
  - 5 points
"""

def draw_star(out, fill, center, size):
    r_outer = size
    r_inner = size // 2.5
    pts = []
    angle_offset = random.uniform(0, 2*np.pi)

    for i in range(10):
        r = r_outer if i % 2 == 0 else r_inner
        angle = i * np.pi / 5 + angle_offset
        x = int(center[0] + r * np.cos(angle))
        y = int(center[1] + r * np.sin(angle))
        pts.append([x, y])

    pts = np.array(pts, np.int32)


    #draw outline
    cv2.polylines(out, [pts], True, 255, 1)
    #draw fill
    cv2.fillPoly(fill, [pts], 255)

def generate_dataset(num_images=NUM_IMAGES):
    print(f"Generating {num_images} images. Shapes will be fully INSIDE the canvas...")

    for i in range(num_images):
        #create our 512x512
        out = np.zeros((CANVAS_SIZE, CANVAS_SIZE), dtype=np.uint8)
        fill = np.zeros((CANVAS_SIZE, CANVAS_SIZE), dtype=np.uint8)

        shape_type = random.choice(['star', 'rect', 'circle', 'dot', 'squiggle', 'ellipse'])

        size = FIXED_SIZE
        # We dont want the shapes eating the border or off the screen.
        # We calculate the zone where we want our shapes to be generated by assumin the max reach of a shape
        # (like a rotating rectangle) is roughly 1.5x the size.
        safe_margin = int(size * 1.5) + 10

        min_coord = safe_margin
        max_coord = CANVAS_SIZE - safe_margin

        center = (random.randint(min_coord, max_coord),
                  random.randint(min_coord, max_coord))

        if shape_type == 'star':
            draw_star(out, fill, center, size)

        elif shape_type == 'circle':
            cv2.circle(out, center, size, 255, 1)
            cv2.circle(fill, center, size, 255, -1)

        elif shape_type == 'rect':
            angle = random.randint(0, 360)
            rect_dims = (size, random.randint(size // 2, int(size * 1.5)))
            box = cv2.boxPoints(((center), (rect_dims), angle))
            box = np.intp(box)
            cv2.drawContours(out, [box], 0, 255, 1)
            cv2.drawContours(fill, [box], 0, 255, -1)

        elif shape_type == 'ellipse':
            axes = (size, random.randint(size//3, size))
            angle = random.randint(0, 360)
            cv2.ellipse(out, center, axes, angle, 0, 360, 255, 1)
            cv2.ellipse(fill, center, axes, angle, 0, 360, 255, -1)

        elif shape_type == 'dot':
            r = random.randint(2, 5)
            cv2.circle(out, center, r, 255, -1)
            cv2.circle(fill, center, r, 255, -1)

        elif shape_type == 'squiggle':
            pts = [center]
            for _ in range(random.randint(1, 2)):
                #constrain squiggle steps to stay somewhat local
                next_pt = (pts[-1][0] + random.randint(-40, 40), pts[-1][1] + random.randint(-40, 40))
                pts.append(next_pt)
            pts = np.array(pts, np.int32)

            cv2.polylines(out, [pts], False, 255, 1)
            cv2.polylines(fill, [pts], False, 255, 1)

        cv2.imwrite(f'data/outlines/shape_{i}.png', out)
        cv2.imwrite(f'data/filled/shape_{i}.png', fill)

if __name__ == "__main__":
    generate_dataset()
